

export const itemList = [
  {
    id: 0,
    type: "consumables",
    key: "VeggieSoup",
    name: "VeggieSoup",
    description: "potion",
    slot: "item",
    rarity: 3,
    element: "base",
    price: 80,
    active: false,
    activate: {
      healHp: 100,
      healMp: 100,
      healSp: 100,
    },
    sprite: new URL ("./../../../assets/sprites/items/consumable/VeggieSoup.png", import.meta.url).href,
  },
  {
    id: 1,
    type: "consumables",
    key: "SmallManaPotion",
    name: "Small Mana Potion",
    description: "potion",
    slot: "item",
    rarity: 3,
    element: "base",
    price: 50,
    active: true,
    activate: {
      healHp: 100,
    },
    sprite: new URL ("./../../../assets/sprites/items/consumable/SmallHp.png", import.meta.url).href,
  },
  {
    id: 2,
    type: "consumables",
    key: "SmallHealthPotion",
    name: "Small Health Potion",
    description: "potion",
    rarity: 3,
    element: "base",
    price: 30,
    active: true,
    activate: {
      healMp: 120,
    },
    sprite: new URL ("./../../../assets/sprites/items/consumable/SmallMana.png", import.meta.url).href,
  },
  {
    id: 3,
    type: "consumables",
    key: "SmallStaminaPotion",
    name: "Small Stamina Potion",
    description: "potion",
    rarity: 3,
    element: "base",
    price: 30,
    active: true,
    activate: {
      healSp: 120,
    },
    sprite: new URL ("./../../../assets/sprites/items/consumable/SmallSp.png", import.meta.url).href,
  },
]